site_name: Project Swashbucklers
copyright: 'copyright © Swashbucklers Inc., All rights reserved.'
theme:
  name: 'material'
  palette:
    primary: indigo
    accent: indigo
pages:
    - Home: index.md
    - Coding Convention: coding_conventions/front_end_convention.md
    - Design Docs: 
      - Infra Chart: design_docs/infra_chart.md
